//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EASTester {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExampleResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExampleResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EASTester.ExampleResources", typeof(ExampleResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;FolderDelete xmlns=&quot;FolderHierarchy:&quot;&gt;
        ///  &lt;SyncKey&gt;5&lt;/SyncKey&gt;
        ///  &lt;ServerId&gt;11&lt;/ServerId&gt;
        ///&lt;/FolderDelete&gt;.
        /// </summary>
        internal static string FolderDelete {
            get {
                return ResourceManager.GetString("FolderDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;FolderSync xmlns=&quot;FolderHierarchy:&quot;&gt;
        ///  &lt;SyncKey&gt;0&lt;/SyncKey&gt;
        ///&lt;/FolderSync&gt;.
        /// </summary>
        internal static string FolderSync {
            get {
                return ResourceManager.GetString("FolderSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;GetItemEstimate xmlns=&quot;GetItemEstimate:&quot;&gt;
        ///  &lt;Collections&gt;
        ///    &lt;Collection&gt;
        ///      &lt;SyncKey xmlns=&quot;AirSync:&quot;&gt;236204501&lt;/SyncKey&gt;
        ///      &lt;CollectionId&gt;1&lt;/CollectionId&gt;
        ///      &lt;Options xmlns=&quot;AirSync:&quot;&gt;
        ///        &lt;FilterType&gt;4&lt;/FilterType&gt;
        ///      &lt;/Options&gt;
        ///    &lt;/Collection&gt;
        ///    &lt;Collection&gt;
        ///      &lt;SyncKey xmlns=&quot;AirSync:&quot;&gt;857662821&lt;/SyncKey&gt;
        ///      &lt;CollectionId&gt;12&lt;/CollectionId&gt;
        ///      &lt;Options xmlns=&quot;AirSync:&quot;&gt;
        ///        &lt;FilterType&gt;3&lt;/FilterType&gt;
        ///      &lt;/Option [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetItemEstimate {
            get {
                return ResourceManager.GetString("GetItemEstimate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Provision xmlns=&quot;Provision:&quot; xmlns:settings=&quot;Settings:&quot;&gt;
        ///  &lt;settings:DeviceInformation&gt;
        ///    &lt;settings:Set&gt;
        ///      &lt;settings:Model&gt;Test 1.0&lt;/settings:Model&gt;
        ///      &lt;settings:IMEI&gt;012345678901234&lt;/settings:IMEI&gt;
        ///      &lt;settings:FriendlyName&gt;My Test App&lt;/settings:FriendlyName&gt;
        ///      &lt;settings:OS&gt;Test OS 1.0&lt;/settings:OS&gt;
        ///      &lt;settings:OSLanguage&gt;English&lt;/settings:OSLanguage&gt;
        ///      &lt;settings:PhoneNumber&gt;555-123-4567&lt;/settings:PhoneNumber&gt;
        ///      &lt;settings:MobileO [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Provision_First {
            get {
                return ResourceManager.GetString("Provision_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Provision xmlns=&quot;Provision:&quot;&gt;
        ///  &lt;Policies&gt;
        ///    &lt;Policy&gt;
        ///      &lt;PolicyType&gt;MS-EAS-Provisioning-WBXML&lt;/PolicyType&gt;
        ///      &lt;PolicyKey&gt;1307199584&lt;/PolicyKey&gt;
        ///      &lt;Status&gt;1&lt;/Status&gt;
        ///    &lt;/Policy&gt;
        ///  &lt;/Policies&gt;
        ///&lt;/Provision&gt;.
        /// </summary>
        internal static string Provision_Second {
            get {
                return ResourceManager.GetString("Provision_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Settings xmlns=&quot;Settings:&quot;&gt;
        ///  &lt;UserInformation&gt;
        ///    &lt;Get/&gt;
        ///  &lt;/UserInformation&gt;
        ///&lt;/Settings&gt;.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
    }
}
